Add Jonah greeting
UMM-CSci-3601-S21/intro-to-git-S21 pull request #15
Opened 2021-01-26 20:01 UTC by Jonah-Northwood

Creates simple method and call.

2021-01-26 20:13 UTC, jquist24 approved these changes, later dismissed
Looks perfect.

2021-01-26 20:17 UTC, lam00071 submitted a review, later dismissed
Greatttt! :D

2021-01-26 20:26 UTC, jquist24 approved these changes, later dismissed
looks good.

2021-01-26 20:33 UTC, lam00071 commented on src/main/java/hellos/Hellos.java
> +    builder.append(jonahSaysHello());
Looks great to me! :D

2021-01-26 20:34 UTC, lam00071 approved these changes, later dismissed
Let's finish this lol

2021-01-26 21:53 UTC, NicMcPhee approved these changes, later dismissed

2021-01-28 01:58 UTC, JacobJenness approved these changes

2021-01-28 02:03 UTC, JacobJenness requested changes
I missed a single semicolon. Whoops

2021-01-28 02:03 UTC, JacobJenness commented on src/main/java/hellos/Hellos.java
> +
```suggestion
}

```

2021-01-28 04:36 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
Yup, this is why it isn't compiling.

2021-01-28 17:21 UTC, schu4276 approved these changes
Looks good!

2021-01-28 17:21 UTC, JacobJenness approved these changes

2021-01-28 17:24 UTC, merged