Add call for Noah's greeting
UMM-CSci-3601-S21/intro-to-git-S21 pull request #16
Opened 2021-01-26 20:01 UTC by zeus-ctrl

Adds the call for Noah's greeting in the builder

2021-01-26 20:12 UTC, JacobJenness approved these changes, later dismissed
LGTM

2021-01-26 20:17 UTC, day00090 approved these changes, later dismissed

2021-01-26 20:17 UTC, day00090 commented on src/main/java/hellos/Hellos.java
This is properly alphabetized.

2021-01-26 20:17 UTC, day00090 commented on src/main/java/hellos/Hellos.java
> +
The formatting looks correct, and the tests pass. I think you're ready to go!

2021-01-26 20:29 UTC, RichardLussier submitted a review, later dismissed
Looks good to go

2021-01-26 20:30 UTC, IsabelleHjelden approved these changes, later dismissed

2021-01-26 20:31 UTC, lam00071 commented on src/main/java/hellos/Hellos.java
> +    builder.append(noahSaysHello());
Hi there hehe doing good job bro.

2021-01-26 20:32 UTC, lam00071 commented on src/main/java/hellos/Hellos.java
> +    builder.append(noahSaysHello());
Right alphabetized too.

2021-01-26 20:32 UTC, lam00071 submitted a review, later dismissed
Let's gooooo

2021-01-26 21:02 UTC, NicMcPhee requested changes

2021-01-26 21:02 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
I wouldn't add a blank line here.

2021-01-26 21:36 UTC, NicMcPhee requested changes
You still have that blank line in Cassie's function that probably should be removed.

2021-01-26 21:36 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
```suggestion
```

2021-01-26 21:55 UTC, NicMcPhee approved these changes
Looks great. In the "real work" I would probably do the change to the MD file at least as a separate commit, and possibly a separate PR, since it's a totally unrelated change. For this, though, I'm totally fine with approving it (and appreciate you noticing and fixing the typo).

2021-01-26 23:16 UTC, day00090 approved these changes, later dismissed
I don't see any issues with the formatting or positioning of the changes.

2021-01-27 00:16 UTC, RichardLussier approved these changes, later dismissed
Looks good

2021-01-27 00:19 UTC, NicMcPhee submitted a review, later dismissed

2021-01-27 01:33 UTC, IsabelleHjelden approved these changes, later dismissed
Looks good

2021-01-27 01:48 UTC, NicMcPhee approved these changes, later dismissed

2021-01-27 04:24 UTC, biruk741 submitted a review, later dismissed

2021-01-27 22:35 UTC, IsabelleHjelden approved these changes
Good to go

2021-01-27 22:37 UTC, merged