Added a greeting for myself.
UMM-CSci-3601-S21/intro-to-git-S21 pull request #17
Opened 2021-01-26 20:01 UTC by biruk741

This one makes it print my name with a greeeting.

2021-01-26 20:10 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +    return "Biruk says 'Yo!'\n";
Dude, "Yo!" isn't a very professional greeting.

2021-01-26 20:12 UTC, NicMcPhee submitted a review, later dismissed
This looks awesome – thanks for the work!

2021-01-26 20:14 UTC, lam00071 commented on src/main/java/hellos/Hellos.java
> +    return "Biruk says 'Yo!'\n";
I mean, yo hahahahahahahagah

2021-01-26 20:15 UTC, lam00071 submitted a review, later dismissed
YooOoOooooO HAGAGAGAGA. Great code ! :D

2021-01-26 20:29 UTC, LloydHilsgen001 submitted a review, later dismissed
Looks good!

2021-01-26 22:18 UTC, NicMcPhee commented
Not that your name for this pull request ("Added a greeting for myself") isn't super helpful when looking at a long list of PR titles since it's not clear who "myself" refers to. I would change that to be a specific reference to your name.

2021-01-26 22:20 UTC, NicMcPhee requested changes
Note that your name for this pull request ("Added a greeting for myself") isn't super helpful when looking at a long list of PR titles since it's not clear who "myself" refers to. I would change that to be a specific reference to your name.

2021-01-26 22:20 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
I probably wouldn't have two blank lines here.

2021-01-27 00:03 UTC, NicMcPhee approved these changes, later dismissed

2021-01-27 07:50 UTC, IsabelleHjelden approved these changes, later dismissed
Looks good!

2021-01-28 02:17 UTC, JacobJenness approved these changes

2021-01-28 02:17 UTC, merged