Blakes greeting
UMM-CSci-3601-S21/intro-to-git-S21 pull request #23
Opened 2021-01-26 20:07 UTC by brwjxxvi

2021-01-26 20:14 UTC, NicMcPhee submitted a review, later dismissed
Very nice – thanks!

2021-01-26 20:15 UTC, Jeklund99 submitted a review, later dismissed
Great

2021-01-26 20:18 UTC, abbas070 commented
Good work!

2021-01-26 20:28 UTC, NicMcPhee approved these changes, later dismissed
That looks fine – thanks.

2021-01-26 20:30 UTC, Jeklund99 submitted a review, later dismissed
Looks good.

2021-01-26 21:45 UTC, NicMcPhee approved these changes
Looks great!

2021-01-26 22:42 UTC, Jeklund99 approved these changes, later dismissed

2021-01-26 22:51 UTC, NicMcPhee approved these changes

2021-01-26 23:45 UTC, DanteMillerDS submitted a review, later dismissed

2021-01-26 23:45 UTC, DanteMillerDS commented
good job!

2021-01-26 23:59 UTC, NicMcPhee approved these changes, later dismissed

2021-01-27 20:39 UTC, helloworld12321 requested changes

2021-01-27 20:39 UTC, helloworld12321 commented on src/main/java/hellos/Hellos.java
> +    builder.append(thomasSaysHello())
```suggestion
    builder.append(thomasSaysHello());
```

Oops, looks like you've got a missing semicolon 🙃

2021-01-27 22:00 UTC, NicMcPhee approved these changes, later dismissed

2021-01-27 22:04 UTC, dahlgrenthomas approved these changes, later dismissed

2021-01-27 22:24 UTC, ellst029 approved these changes, later dismissed

2021-01-27 22:30 UTC, halleypaulson approved these changes, later dismissed

2021-01-27 22:41 UTC, helloworld12321 submitted a review, later dismissed
Sorry it took me so long to re-review. Looks great, Blake! 🙂

2021-01-27 22:43 UTC, lam00071 submitted a review, later dismissed
let's get this doneeeeeee

2021-01-28 00:32 UTC, Jeklund99 approved these changes, later dismissed

2021-01-28 01:34 UTC, JacobJenness approved these changes

2021-01-28 01:35 UTC, helloworld12321 approved these changes
Here's hoping it'll go through!

2021-01-28 01:50 UTC, merged