Adds the 'builder' call and implements the method for Jadyn.
UMM-CSci-3601-S21/intro-to-git-S21 pull request #5
Opened 2021-01-26 20:00 UTC by JadynSondrol

This adds the 'builder' call and implements the method for Jadyn's greeting.

2021-01-26 20:12 UTC, IsabelleHjelden submitted a review, later dismissed
Looks good!

2021-01-26 20:16 UTC, halleypaulson submitted a review, later dismissed
Approved!

2021-01-26 21:06 UTC, halleypaulson submitted a review, later dismissed
looks good

2021-01-26 21:51 UTC, NicMcPhee requested changes

2021-01-26 21:51 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +  private String JadynSaysHello() {
The "common standard" is that methods in Java start with a lowercase letter, so `jadynSaysHello` instead of `JadynSaysHello`.

2021-01-26 21:51 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +
I'd remove this blank line – we don't really want stray blank lines in method definitions.

2021-01-26 23:51 UTC, NicMcPhee submitted a review, later dismissed

2021-01-26 23:55 UTC, NicMcPhee approved these changes

2021-01-27 00:22 UTC, IsabelleHjelden approved these changes
looking good!

2021-01-27 00:25 UTC, merged