Alice's Hello
UMM-CSci-3601-S21/intro-to-git-S21 pull request #8
Opened 2021-01-26 20:00 UTC by ellst029

This is my hello! Hello!

2021-01-26 20:15 UTC, JadynSondrol approved these changes, later dismissed

2021-01-26 20:15 UTC, JacobJenness requested changes, later dismissed
Line 21 should have the following.
`builder.append(aliceSaysHello());`
This will make sure that `Hellos.java` will print your greeting.

2021-01-26 23:01 UTC, floogulinc commented on src/main/java/hellos/Hellos.java
> +alice-greeting
You probably didn't mean to leave this in from merging!
```suggestion
```

2021-01-26 23:03 UTC, NicMcPhee commented
If things get weird, I would definitely recommend pulling the latest version of your branch to your computer, and then working on things in VS Code. You can run the tests there, and it will check that your code compiles, etc.

2021-01-27 00:02 UTC, NicMcPhee requested changes

2021-01-27 00:02 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +    builder.append(
This isn't a complete statement/line. You probably wanted:

```suggestion
    builder.append(aliceSaysHello());
```

2021-01-27 00:02 UTC, NicMcPhee commented on src/main/java/hellos/Hellos.java
> +  private String aliceSaysHello(){
The "standard" is to have a space before the curly brace at the start of a method:

```suggestion
  private String aliceSaysHello() {
```

2021-01-27 22:17 UTC, NicMcPhee approved these changes
That looks great – thanks for fixing those compiler errors.

2021-01-27 22:31 UTC, merged

2021-01-27 22:32 UTC, halleypaulson approved these changes